version: '3.8'

services:

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - config-server

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
      - config-server
      - mysql-auth

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
      - config-server
      - mysql-user

  mentor-service:
    build: ./mentor-service
    container_name: mentor-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql-mentor

  skill-service:
    build: ./skill-service
    container_name: skill-service
    ports:
      - "8084:8084"
    depends_on:
      - mysql-skill

  session-service:
    build: ./session-service
    container_name: session-service
    ports:
      - "8085:8085"
    depends_on:
      - mysql-session
      - rabbitmq

  review-service:
    build: ./review-service
    container_name: review-service
    ports:
      - "8086:8086"
    depends_on:
      - mysql-review

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8087:8087"
    depends_on:
      - rabbitmq
    environment:
      MAIL_PASSWORD: kxjrljsibkmhqvau

  test-service:
    build: ./test-service
    container_name: test-service
    ports:
      - "9000:9000"

  # ---------------- DATABASES ----------------

  mysql-auth:
    image: mysql:8
    container_name: mysql-auth
    environment:
      MYSQL_DATABASE: skillsync_auth
      MYSQL_USER: javauser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  mysql-user:
    image: mysql:8
    container_name: mysql-user
    environment:
      MYSQL_DATABASE: skillsync_user
      MYSQL_USER: javauser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"

  mysql-mentor:
    image: mysql:8
    container_name: mysql-mentor
    environment:
      MYSQL_DATABASE: skillsync_mentor
      MYSQL_USER: javauser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  mysql-skill:
    image: mysql:8
    container_name: mysql-skill
    environment:
      MYSQL_DATABASE: skillsync_skill
      MYSQL_USER: javauser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  mysql-session:
    image: mysql:8
    container_name: mysql-session
    environment:
      MYSQL_DATABASE: skillsync_session
      MYSQL_USER: javauser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  mysql-review:
    image: mysql:8
    container_name: mysql-review
    environment:
      MYSQL_DATABASE: skillsync_review
      MYSQL_USER: javauser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  # ---------------- INFRA ----------------

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"