spring:
  application:
    name: review-service

  profiles:
    active: local   # ✅ added

  config:
    import: "optional:classpath:application-default.yml,optional:configserver:http://localhost:8888"